import { Inter } from "next/font/google";
import "./globals.css";
import RootHeader from "@/components/RootHeader";
import RootFooter from "@/components/RootFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ko">
            <body>
                <RootHeader />
                
                <main>{children}</main>
                
                <RootFooter />
            </body>
        </html>
    );
}
